insert into stadium (name) values ('대전 한화생명 이글스파크');
insert into stadium (name) values ('잠실종합운동장');
insert into stadium (name) values ('사직 야구장');

insert into team (STADIUM_ID, NAME) values ( 1, '한화 이글스' );
insert into team (STADIUM_ID, NAME) values ( 2, '두산 베어스' );
insert into team (STADIUM_ID, NAME) values ( 3, '롯데 자이언츠' );
insert into team (STADIUM_ID, NAME) values ( 1, '패스트캠퍼스 백엔드 부트캠프 5기' );

insert into position_t values (1, 'Pitcher', 'P', '투수');
insert into position_t values (2, 'Catcher', 'C', '포수');
insert into position_t values (3, 'First Baseman', 'FB', '1루수');
insert into position_t values (4, 'Second Baseman', 'SB', '2루수');
insert into position_t values (5, 'Third Baseman', 'TB', '3루수');
insert into position_t values (6, 'Shortstop', 'SS', '유격수');
insert into position_t values (7, 'Left Fielder', 'LF', '좌익수');
insert into position_t values (8, 'Center Fielder', 'CF', '중견수');
insert into position_t values (9, 'Right Fielder', 'RF', '우익수');

insert into player (team_id, name, position) values (1, '이태양', 'P');
insert into player (team_id, name, position) values (1, '최재훈', 'C');
insert into player (team_id, name, position) values (1, '김인환', 'FB');
insert into player (team_id, name, position) values (1, '정은원', 'SB');
insert into player (team_id, name, position) values (1, '노시환', 'TB');
insert into player (team_id, name, position) values (1, '오선진', 'SS');
insert into player (team_id, name, position) values (1, '채은성', 'LF');
insert into player (team_id, name, position) values (1, '오그레디', 'CF');
insert into player (team_id, name, position) values (1, '이진영', 'RF');
insert into player (team_id, name, position) values (2, '김선우', 'P');
insert into player (team_id, name, position) values (2, '양의지', 'C');
insert into player (team_id, name, position) values (2, '양석환', 'FB');
insert into player (team_id, name, position) values (2, '김재호', 'SB');
insert into player (team_id, name, position) values (2, '허경민', 'TB');
insert into player (team_id, name, position) values (2, '전민재', 'SS');
insert into player (team_id, name, position) values (2, '김재환', 'LF');
insert into player (team_id, name, position) values (2, '정수빈', 'CF');
insert into player (team_id, name, position) values (2, '조수행', 'RF');
insert into player (team_id, name, position) values (3, '댄 스트레일리', 'P');
insert into player (team_id, name, position) values (3, '유강남', 'C');
insert into player (team_id, name, position) values (3, '고승민', 'FB');
insert into player (team_id, name, position) values (3, '안치홍', 'SB');
insert into player (team_id, name, position) values (3, '한동희', 'TB');
insert into player (team_id, name, position) values (3, '노진혁', 'SS');
insert into player (team_id, name, position) values (3, '황성빈', 'LF');
insert into player (team_id, name, position) values (3, '안권수', 'CF');
insert into player (team_id, name, position) values (3, '잭 렉스', 'RF');
insert into player (team_id, name, position) values (4, '김주원', 'P');

select * from stadium;
select * from team;
select * from position_t;
select * from player;
select * from position_team_player;