drop table if exists out_player;
drop table if exists player cascade;
drop table if exists team cascade;
drop table if exists stadium cascade;

create table stadium (
    id          bigint          generated by default as identity,
    name        varchar(32)     not null unique,
    created_at  timestamp       not null default now(),
    primary key (id)
);

create table team (
    id          bigint          generated by default as identity,
    stadium_id  bigint,
    name        varchar(32)     not null unique,
    created_at  timestamp       not null default now(),
    primary key (id),
    foreign key (stadium_id) references stadium(id)
);

create table player (
    id          bigint          generated by default as identity,
    team_id     bigint          not null,
    name        varchar(32)     not null,
    position    varchar(20)     not null,
    created_at  timestamp       not null default now(),
    primary key (id),
    foreign key(team_id) references team(id),
    constraint team_position unique (team_id, position)
);

create table out_player (
    id          bigint          generated by default as identity,
    player_id   bigint          not null,
    reason      varchar(50),
    created_at  timestamp       not null default now(),
    primary key (id),
    foreign key(player_id) references player(id)
);